FROM golang:1.21.2-alpine3.18 as build

# Set destination for COPY
WORKDIR /api

# Download Go modules
COPY go.mod go.sum ./
RUN go mod download

# Copy the source code. Note the slash at the end, as explained in
# https://docs.docker.com/engine/reference/builder/#copy
COPY ./ ./
