version: '3.8'

services:
  db:
    image: postgres:alpine3.18
    volumes:
      - ./databases/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_NAME=pg
      - POSTGRES_USER=pg
      - POSTGRES_PASSWORD=pg
    ports:
      - '5432:5432'
  # api:
  #   image: api
  #   build: .
  #   restart: always
  #   ports:
  #     - "8282:8282"