version: '3.8'

services:
  db:
    image: postgres:alpine3.18
    volumes:
      - ./databases/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_NAME=pg
      - POSTGRES_USER=pg
      - POSTGRES_PASSWORD=pg
    ports:
      - '5432:5432'
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U pg -d pg"]
      interval: 1s
      timeout: 1s
  api:
    image: api
    build: .
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8282:8282"
    environment:
      - DATABASE_URL=postgres://pg:pg@db:5432/pg
    command: ["sh", "-c", "./backend"]